In [8]:
import pandas as pd

In [9]:
df = pd.read_csv("spotify_millsongdata.csv")

In [10]:
df.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [11]:
df.tail()

,artist,song,link,text
57645,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \r\nLet the angels fly...
57646,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \r\nMore power \r\nPowe...
57647,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \r\nis something i'll believe \...
57648,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \r\nam i frightened \r\nwhere ...
57649,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \r\nmake yourself at home \r\ni'm a ...

In [12]:
df.shape

(57650, 4)

In [13]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [14]:
df = df.sample(5000).drop('link', axis=1).reset_index(drop=True)

In [15]:
df.head(10)

,artist,song,text
0,Mariah Carey,Now That I Know,I never knew \r\nIf I could believe in you \...
1,Celine Dion,All The Way,When somebody loves you \r\nIt's no good unle...
2,Elvis Costello,Dr. Luther's Assistant,Everything seems so tranquil \r\nHome movies ...
3,Don Henley,Not Enough Love In The World,Sometimes I wonder where it is love goes \r\n...
4,Jackson Browne,A Child In These Hills,I am a child in these hills \r\nI am away \r...
5,Overkill,Unholy,"Gimme, gimme, gimme some candy baby \r\nI got..."
6,Styx,Queen Of Spades,Day into night she's with me \r\nHow sweet is...
7,Yolanda Adams,I'm Grateful,"I woke up this morning, closed in my right min..."
8,Poison,Untitled,(here it comes) \r\nWell funky monkey's in th...
9,Who,Put The Money Down,"I got lost in the back streets, trying to get ..."

In [16]:
df['text'][0]

"I never knew  \r\nIf I could believe in you  \r\nI thought I was just a diversion  \r\nAnd you were killing some time  \r\nMy friends they told me  \r\nTo leave you  \r\n  \r\nThey said you would never  \r\nBe mine  \r\nBut you gave me your love  \r\nAnd you said I'm the one  \r\nYou want for the rest of  \r\nYour life  \r\n  \r\nNow that I know  \r\nThat you want me for me  \r\nI can be what you want  \r\nI can be what you need  \r\nNow that I know  \r\nThat your love is for real  \r\nI can finally see  \r\nThis is not make believe anymore  \r\n  \r\nI was afraid  \r\nIt was all a masquerade  \r\nThat I was only a plaything  \r\nAnd you would leave me behind  \r\nBut now I feel so secure  \r\nBy your side  \r\nI can conquer the world  \r\nI gave you my love  \r\nAnd I know you're the one  \r\nI want for the rest  \r\nOf my life  \r\n  \r\nNow that I know  \r\nThat you want me for me  \r\nI can be what you want  \r\nI can be what you need  \r\nNow that I know  \r\nThat your love is for real  \r\nI can finally see  \r\nThis is not make believe anymore  \r\n  \r\nNow that I know  \r\nThat you want me for me  \r\nI can be what you want  \r\nI can be what you need  \r\nNow that I know  \r\nThat your love is for real  \r\nI can finally see  \r\nThis is not make believe anymore  \r\n  \r\n(I really feel it)  \r\nSo much love  \r\n(I really feel it)  \r\nSo much joy  \r\n(I feel it)  \r\nSweet sweet ecstasy  \r\n'Cause you opened my eyes  \r\nAnd I realize  \r\nYour love is for real  \r\n  \r\nNow that I know  \r\nThat you want me for me  \r\nI can be what you want  \r\nI can be what you need  \r\nNow that I know  \r\nThat your love is for real  \r\nI can finally see  \r\nThis is not make believe anymore  \r\n\r\n"

In [17]:
df = df.sample(5000)

In [18]:
df.shape

(5000, 3)

Text Cleaning/ Text Preprocessing

In [19]:
df['text'] = df['text'].str.lower().replace(r'^\w\s', ' ').replace(r'\n', ' ', regex = True)

In [20]:
df.tail(5)

,artist,song,text
1273,Glen Campbell,You're The One,many's the time i looked in the water \r and ...
961,Rod Stewart,Hot Legs,who's that knocking on my door \r it's gotta ...
4309,Ray Charles,Just A Little Lovin',"just a little lovin, yeah \r will go a long w..."
1291,John Prine,The Oldest Baby In The World,she's got the mind of a child \r and a body p...
2482,Korn,Need To,"i, i am confused, fighting myself \r wanting ..."

In [21]:
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_rus is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package bllip_wsj_no_aux is already up-to-date!
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package book_grammars is already up-to-date!
[nltk_data]    | Downloading package brown to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading package chat80 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package chat80 is already up-to-date!
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package city_database is already up-to-date!
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package comparative_sentences is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package comtrans to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package comtrans is already up-to-date!
[nltk_data]    | Downloading package conll2000 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2000 is already up-to-date!
[nltk_data]    | Downloading package conll2002 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2002 is already up-to-date!
[nltk_data]    | Downloading package conll2007 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2007 is already up-to-date!
[nltk_data]    | Downloading package crubadan to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package crubadan is already up-to-date!
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package dependency_treebank is already up-to-date!
[nltk_data]    | Downloading package dolch to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package dolch is already up-to-date!
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package europarl_raw is already up-to-date!
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package extended_omw is already up-to-date!
[nltk_data]    | Downloading package floresta to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package floresta is already up-to-date!
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package framenet_v15 is already up-to-date!
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package framenet_v17 is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package ieer to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ieer is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package indian to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package indian is already up-to-date!
[nltk_data]    | Downloading package jeita to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package jeita is already up-to-date!
[nltk_data]    | Downloading package kimmo to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package kimmo is already up-to-date!
[nltk_data]    | Downloading package knbc to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package knbc is already up-to-date!
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package large_grammars is already up-to-date!
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package lin_thesaurus is already up-to-date!
[nltk_data]    | Downloading package mac_morpho to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mac_morpho is already up-to-date!
[nltk_data]    | Downloading package machado to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package machado is already up-to-date!
[nltk_data]    | Downloading package masc_tagged to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package masc_tagged is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker_tab to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_ne_chunker_tab is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger_tab to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger_tab is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package moses_sample is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package mte_teip5 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mte_teip5 is already up-to-date!
[nltk_data]    | Downloading package mwa_ppdb to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mwa_ppdb is already up-to-date!
[nltk_data]    | Downloading package names to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package nombank.1.0 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nombank.1.0 is already up-to-date!
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nonbreaking_prefixes is already up-to-date!
[nltk_data]    | Downloading package nps_chat to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nps_chat is already up-to-date!
[nltk_data]    | Downloading package omw to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package opinion_lexicon is already up-to-date!
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package panlex_swadesh is already up-to-date!
[nltk_data]    | Downloading package paradigms to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package paradigms is already up-to-date!
[nltk_data]    | Downloading package pe08 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pe08 is already up-to-date!
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package perluniprops is already up-to-date!
[nltk_data]    | Downloading package pil to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pil is already up-to-date!
[nltk_data]    | Downloading package pl196x to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pl196x is already up-to-date!
[nltk_data]    | Downloading package porter_test to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package porter_test is already up-to-date!
[nltk_data]    | Downloading package ppattach to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ppattach is already up-to-date!
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package problem_reports is already up-to-date!
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package product_reviews_1 is already up-to-date!
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package product_reviews_2 is already up-to-date!
[nltk_data]    | Downloading package propbank to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package propbank is already up-to-date!
[nltk_data]    | Downloading package pros_cons to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pros_cons is already up-to-date!
[nltk_data]    | Downloading package ptb to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ptb is already up-to-date!
[nltk_data]    | Downloading package punkt to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package punkt_tab to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package punkt_tab is already up-to-date!
[nltk_data]    | Downloading package qc to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package qc is already up-to-date!
[nltk_data]    | Downloading package reuters to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package reuters is already up-to-date!
[nltk_data]    | Downloading package rslp to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package rslp is already up-to-date!
[nltk_data]    | Downloading package rte to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package rte is already up-to-date!
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sample_grammars is already up-to-date!
[nltk_data]    | Downloading package semcor to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package semcor is already up-to-date!
[nltk_data]    | Downloading package senseval to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package senseval is already up-to-date!
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sentence_polarity is already up-to-date!
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sentiwordnet is already up-to-date!
[nltk_data]    | Downloading package shakespeare to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sinica_treebank is already up-to-date!
[nltk_data]    | Downloading package smultron to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package smultron is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package spanish_grammars is already up-to-date!
[nltk_data]    | Downloading package state_union to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package state_union is already up-to-date!
[nltk_data]    | Downloading package stopwords to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package subjectivity is already up-to-date!
[nltk_data]    | Downloading package swadesh to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package swadesh is already up-to-date!
[nltk_data]    | Downloading package switchboard to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package switchboard is already up-to-date!
[nltk_data]    | Downloading package tagsets to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package tagsets is already up-to-date!
[nltk_data]    | Downloading package tagsets_json to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package tagsets_json is already up-to-date!
[nltk_data]    | Downloading package timit to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package timit is already up-to-date!
[nltk_data]    | Downloading package toolbox to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package toolbox is already up-to-date!
[nltk_data]    | Downloading package treebank to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package udhr to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package udhr is already up-to-date!
[nltk_data]    | Downloading package udhr2 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package udhr2 is already up-to-date!
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package unicode_samples is already up-to-date!
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package universal_tagset is already up-to-date!
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package universal_treebanks_v20 is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package vader_lexicon is already up-to-date!
[nltk_data]    | Downloading package verbnet to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package verbnet is already up-to-date!
[nltk_data]    | Downloading package verbnet3 to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package verbnet3 is already up-to-date!
[nltk_data]    | Downloading package webtext to
[nltk_data]    |     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Package webtext is already up-to-date!
[nltk_data]    | Downloading package wmt15_eval to

True

In [22]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

In [23]:
stemmer = PorterStemmer()

In [24]:
def token(txt):
    tokens = word_tokenize(txt)  # Tokenizes text into words
    a = [stemmer.stem(w) for w in tokens]  # Applies stemming to each token
    return " ".join(a)

In [25]:
print(token("you are beautiful, beauty"))

you are beauti , beauti

In [26]:
df['text'].apply(lambda x: token(x))

3981    when the rose . slap your face say your pain i...
1454    hometown , same town blue same old wall close ...
774     easi lover she 'll get a hold on you believ it...
2999    first choru intro : [ d ] ... [ a7 ] ... [ d ]...
3934    one way in and one way out you do n't know wha...
                              ...
1273    mani 's the time i look in the water and had n...
961     who 's that knock on my door it 's got ta be a...
4309    just a littl lovin , yeah will go a long way w...
1291    she 's got the mind of a child and a bodi peak...
2482    i , i am confus , fight myself want to give in...
Name: text, Length: 5000, dtype: object

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [28]:
tfid = TfidfVectorizer(analyzer = 'word', stop_words='english')

In [29]:
matrix = tfid.fit_transform(df['text'])

In [30]:
similar = cosine_similarity(matrix)

In [31]:
similar[0]

array([1.        , 0.08980395, 0.05634705, ..., 0.03910349, 0.06402218,
       0.0322103 ])

In [32]:
df.tail(50)

,artist,song,text
2166,Howard Jones,Wanders To You,it's been so long since i slept \r the good b...
1028,Neil Young,After The Goldrush,"well, i dreamed i saw the knights in armor com..."
1997,Natalie Cole,Snowfall On The Sahara,your love like wine \r tasting sweeter to me ...
4318,Bob Dylan,Honest With Me,"well, i'm stranded in the city that never slee..."
2873,Cliff Richard,Marked With Death,how can i bear this? show me \r how can i sur...
4464,Nina Simone,End Of The Line,this is the end of the line \r i've clearly r...
4505,Devo,Freedom Of Choice,a victim of collision on the open sea \r nobo...
682,Marilyn Manson,Evidence,you have eyes that lead me on \r and a body t...
828,Primus,Walk,can't you see i'm easily bothered by persistan...
4804,Blur,Good Song,"waiting, i got no town to hide in \r the coun..."
974,Wu-Tang Clan,Shaolin Worldwide,who's the knucklehead wantin' respect \r \r...
2012,John Prine,Six O'clock News,wanda had a baby in nineteen fifty one. \r th...
3661,System Of A Down,Thetawaves,"the unsettled mind is at times an ally, \r le..."
2224,Iron Maiden,Another Life,as i lay here lying on my bed \r sweet voices...
4649,Patsy Cline,Walking After Midnight,i go out walkin' after midnight \r out in the...
835,NOFX,My Name Is Bud,they're always doin' fry \r tryin' to get me ...
854,Leann Rimes,Till We Ain't Strangers Anymore,(feat. bon jovi) \r \r it might be hard to ...
3422,Don McLean,Winterwood,"no-one can take your place with me, \r and ti..."
4442,Louis Armstrong,Sun Showers,sun showers \r it might rain \r sun will shi...
3286,Guided By Voices,Planet Score,you could have gotten to know \r in the tinte...
4873,Mud,Diana,i'm so young and your so old \r this my darli...
4033,Tom Waits,Drunk On The Moon,tight-slacked clad girls on the graveyard shif...
4726,ZZ Top,"I Don't Wanna Lose, Lose, You",sometimes it's hard to make things clear \r o...
2002,Foo Fighters,Monkey Wrench,what have we done with innocence? \r it disap...
2716,Gloria Estefan,Hot Summer Nights,in the time before the twilight \r settles on...
1678,Unseen,Live In Fear,live in fear \r live in fear \r live in fear...
2985,Wanda Jackson,Song Of The Wind,i see the shadows as they come to welcome the ...
560,David Bowie,Arnold Layne,arnold layne \r had a strange hobby \r colle...
1765,Planetshakers,I Believe,heard story just the other day \r about man w...
886,Faith No More,Mouth To Mouth,you tied the knot \r a legend is what you bou...
2583,Foreigner,I'm Gonna Win,"another dark night, in the city \r and my pro..."
3561,Aerosmith,"Shame, Shame, Shame",shame shame shame on you miss roxy \r shame s...
735,Ellie Goulding,Bittersweet,your arms around me come undone \r makes my h...
4882,Cheap Trick,The Ballad Of TV Violence,i needed a girl to give me some love \r i nee...
1831,Doobie Brothers,Carry Me Away,"there was a place in east st. louis, it was in..."
902,Elvis Costello,Couldn't You Keep That To Yourself,the tiny slip at midnight \r a little sip at ...
31,Chicago,Poem For The People,if the people only knew \r if they could visu...
3347,Everclear,Misery Whip,walking wounded with a belly full of pain \r ...
650,Beautiful South,Just Checkin',"i came in here, just to see his guilty face \..."
3875,David Guetta,Choose,"ah yeah! \r ah, ah yeah \r choose you wanna ..."
1837,Pearl Jam,Don't Believe In Christmas,well \r mom and dad \r said we could \r so ...
4050,Hanson,Georgia,"georgia, you know that you've been on my mind ..."
1378,Willie Nelson,Have I Told You Lately That I Love You,have i told you lately that i love you \r cou...
2883,Vince Gill,Nothing Like A Woman,oh there's nothin' like a woman \r when you'r...
3296,John Denver,Four Strong Winds,"four strong winds that blow lonely, seven seas..."
1273,Glen Campbell,You're The One,many's the time i looked in the water \r and ...
961,Rod Stewart,Hot Legs,who's that knocking on my door \r it's gotta ...
4309,Ray Charles,Just A Little Lovin',"just a little lovin, yeah \r will go a long w..."
1291,John Prine,The Oldest Baby In The World,she's got the mind of a child \r and a body p...
2482,Korn,Need To,"i, i am confused, fighting myself \r wanting ..."

In [34]:
df[df['song'] == "Misery Whip"].index[0]

np.int64(3347)

Recommender Function

In [39]:
def recommender(song_name):
    idx = df[df['song'] == song_name].index[0]
    distance = sorted(list(enumerate(similar[idx])), reverse=True, key = lambda x:x[1])
    song = []
    for s_id in distance[1:21]:
        song.append(df.iloc[s_id[0]].song)
    return song

In [40]:
recommender("You're The One")

['Easy',
 'All I Can Do',
 'I Cry',
 "It's Never Easy To Say Goodbye",
 'Easy To Love',
 "It Ain't Easy",
 'Easy Come, Easy Go',
 'Falling',
 'Tell Me Everything',
 "Ain't That Love",
 'Mona Lisa',
 'Let Me Down Easy',
 "Ain't That Lovin' You Baby",
 'Cry Baby',
 'Me And My Baby',
 'Falling Down',
 'Wherever I Go',
 'Die In Your Arms',
 'I Never Loved A Man',
 'Born To Be Bad']

In [41]:
import pickle

In [42]:
pickle.dump(similar, open("similarity", "wb"))

In [43]:
pickle.dump(df, open("df", "wb"))

In [44]:
with open("df.pkl", "wb") as df_file:
    pickle.dump(df, df_file)

In [45]:
with open("similarity.pkl", "wb") as similarity_file:
    pickle.dump(similar, similarity_file)